[workspace]
resolver='2'
package.edition="2024"
package.version = "0.1.7-alpha.0"

members = [ "libffmpeg" ]

[workspace.lints.clippy]
pedantic = { level = "warn", priority = 0 }
missing_errors_doc = { level = "allow", priority = 1 }
panic = { level = "warn", priority = 1 }
implicit_hasher = { level = "allow", priority = 1 }
missing_panics_doc = { level = "allow", priority = 1 }
cast_possible_truncation = { level = "allow", priority = 1 }
cast_possible_wrap = { level = "allow", priority = 1 }
cast_sign_loss = { level = "allow", priority = 1 }
cast_lossless = { level = "allow", priority = 1 }
cast_precision_loss = { level = "allow", priority = 1 }
large_enum_variant = { level = "allow", priority = 1 }
result_large_err = { level = "allow", priority = 1 }
needless_pass_by_value = { level = "allow", priority = 1 }
large_futures = { level = "allow", priority = 1 }
match_same_arms = { level = "allow", priority = 1 }


[workspace.dependencies]
liberror = { git = "https://github.com/charliethomson/liberror", rev = "b75e9a2" }
libcmd = { git = "https://github.com/charliethomson/libcmd", rev = "a84f673" }
libsignal = { git = "https://github.com/charliethomson/libsignal", rev = "18e2c46" }
libwhich = { git = "https://github.com/charliethomson/which", rev = "b6aaf66" }

libffmpeg = { path = "./libffmpeg" }

serde = { version = "1.0.219", features = ["derive"] }
thiserror = { version = "2.0.16" }
tokio = { version = "1.47.1", features = ["rt", "process", "sync", "time", "macros"] }
tokio-util = { version = "0.7.16" }
tracing = { version = "0.1.41", features = ["valuable"] }
valuable = { version = "0.1.1", features = ["derive"] }
