[package]
name = "libffmpeg"
version.workspace = true
edition.workspace = true

[dependencies]
liberror.workspace = true
libcmd.workspace = true
libwhich.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
valuable.workspace = true

[dev-dependencies]
libsignal.workspace = true
anyhow = { version = "1" }
clap = { version = "4", features = ["derive"] }
humansize = { version = "2" }
humantime = { version = "2" }

[lints]
workspace = true
